In [4]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [5]:
u = np.array([2, 3, 1, 4])
u

array([2, 3, 1, 4])

In [11]:
u[0] = 5
u

array([5, 3, 1, 4])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [1]:
u = [
    [1, 3, 0],
    [2, 0, 4],
    [1, 3, 2]
]
type(u)

list

In [16]:
u = np.array([
     [1, 3, 0],
    [2, 0, 4],
    [1, 3, 2]
])

u[:, 1] = [0, 0, 0]
u

array([[1, 0, 0],
       [2, 0, 4],
       [1, 0, 2]])

In [22]:
n = np.random.rand(5, 3)
n

array([[0.80846371, 0.58325495, 0.14382664],
       [0.11268314, 0.73343573, 0.85944179],
       [0.97414862, 0.1547745 , 0.86686606],
       [0.29236274, 0.88773919, 0.47378659],
       [0.04581362, 0.75721191, 0.23657453]])

In [23]:
np.random.seed(2)
np.random.rand(3,2)


array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482]])

In [24]:
np.random.seed(2)
np.random.rand(3,2)


array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482]])

In [25]:
np.random.seed(2)
np.random.randn(3,2)


array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737]])

In [26]:
np.random.seed(2)
np.random.randint(low=10, high=100,size=(3,2))

array([[50, 25],
       [82, 32],
       [53, 92]])

In [31]:
n = np.arange(5)
n

array([0, 1, 2, 3, 4])

In [32]:
x = n * 2
x

array([0, 2, 4, 6, 8])

In [34]:
a = n + x
a

array([ 0,  3,  6,  9, 12])